<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Apya.Platform.Ai</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Apya.Platform.Ai.Application.Contracts\Apya.Platform.Ai.Application.Contracts.csproj" />
    <ProjectReference Include="..\Apya.Platform.HttpApi\Apya.Platform.HttpApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="10.0.2" />
  </ItemGroup>

</Project>
