<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Apya.Platform.Ai</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Apya.Platform.Ai.Domain\Apya.Platform.Ai.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" Version="10.0.2" />
  </ItemGroup>

</Project>
