<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Apya.Platform.Ai</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Apya.Platform.Domain.Shared\Apya.Platform.Domain.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Validation" Version="10.0.2" />
  </ItemGroup>

</Project>
